fifth attempt to fix XML issues

diff --git a/shell/bashrc_shared b/shell/bashrc_shared
--- a/shell/bashrc_shared
+++ b/shell/bashrc_shared
@@ -63,6 +63,41 @@ pub_images () {
   local SIF="${HOME}/containers/ros_humble_perception.sif"
 
   local CPU_IP="130.89.6.254"
+  local GPU_IP
+  GPU_IP=$(hostname -I | tr " " "\n" | awk '/^10[.]/ {print; exit} END{ if(!NR) print "127.0.0.1" }')
+  local FASTDDS_FILE="${HOME}/.fastdds_unicast_runtime.xml"
+  cat > "${FASTDDS_FILE}" <<EOF
+<?xml version="1.0" encoding="UTF-8" ?>
+<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
+  <transport_descriptors>
+    <transport_descriptor>
+      <transport_id>udp_only</transport_id>
+      <type>UDPv4</type>
+    </transport_descriptor>
+  </transport_descriptors>
+  <participant profile_name="unicast_participant" is_default_profile="true">
+    <rtps>
+      <useBuiltinTransports>false</useBuiltinTransports>
+      <userTransports><transport_id>udp_only</transport_id></userTransports>
+      <builtin>
+        <initialPeersList>
+          <locator><udpv4><address>${CPU_IP}</address></udpv4></locator>
+          <locator><udpv4><address>${GPU_IP}</address></udpv4></locator>
+        </initialPeersList>
+        <avoid_builtin_multicast>true</avoid_builtin_multicast>
+      </builtin>
+      <throughputController>
+        <bytesPerPeriod>2097152</bytesPerPeriod>
+        <periodMillisecs>0</periodMillisecs>
+      </throughputController>
+    </rtps>
+  </participant>
+</profiles>
+EOF
+
+  if [ ! -f "${FASTDDS_FILE}" ]; then
+    echo "[pub_images] Warning: failed to write ${FASTDDS_FILE}" >&2
+  fi
 
   local LOOP_FLAG=""
   if [[ "${1:-}" == "loop" ]]; then
@@ -78,48 +113,8 @@ pub_images () {
     export ROS_DOMAIN_ID=42
     export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
     export ROS_LOCALHOST_ONLY=0
-    export FASTDDS_DEFAULT_PROFILES_FILE=\$HOME/.fastdds_unicast_runtime.xml
-    export FASTRTPS_DEFAULT_PROFILES_FILE=\$HOME/.fastdds_unicast_runtime.xml
-
-    CPU_IP=\"${CPU_IP}\"
-    GPU_IP=\$(hostname -I | tr \" \" \"\\n\" | awk '/^10[.]/ {print; exit} END{ if(!NR) print \"127.0.0.1\" }')
-    FASTDDS_FILE=\"\$HOME/.fastdds_unicast_runtime.xml\"
-    export FASTDDS_DEFAULT_PROFILES_FILE=\"\$FASTDDS_FILE\"
-    export FASTRTPS_DEFAULT_PROFILES_FILE=\"\$FASTDDS_FILE\"
-    cat > \"\$FASTDDS_FILE\" <<EOF
-<?xml version=\"1.0\" encoding=\"UTF-8\"?>
-<profiles xmlns=\"http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles\">
-  <transport_descriptors>
-    <transport_descriptor>
-      <transport_id>udp_only</transport_id>
-      <type>UDPv4</type>
-    </transport_descriptor>
-  </transport_descriptors>
-  <participant profile_name=\"unicast_participant\" is_default_profile=\"true\">
-    <rtps>
-      <useBuiltinTransports>false</useBuiltinTransports>
-      <userTransports><transport_id>udp_only</transport_id></userTransports>
-      <builtin>
-        <initialPeersList>
-          <locator><udpv4><address>\${CPU_IP}</address></udpv4></locator>
-          <locator><udpv4><address>\${GPU_IP}</address></udpv4></locator>
-        </initialPeersList>
-        <avoid_builtin_multicast>true</avoid_builtin_multicast>
-      </builtin>
-      <throughputController>
-        <bytesPerPeriod>2097152</bytesPerPeriod>
-        <periodMillisecs>0</periodMillisecs>
-      </throughputController>
-    </rtps>
-  </participant>
-</profiles>
-EOF
-    if [ ! -f \"\$FASTDDS_FILE\" ]; then
-      echo \"[pub_images] Failed to create \$FASTDDS_FILE\" >&2
-    else
-      echo \"[pub_images] DDS profile -> \$FASTDDS_FILE\"
-      ls -l \"\$FASTDDS_FILE\" || true
-    fi
+    export FASTDDS_DEFAULT_PROFILES_FILE='$HOME/.fastdds_unicast_runtime.xml'
+    export FASTRTPS_DEFAULT_PROFILES_FILE='$HOME/.fastdds_unicast_runtime.xml'
 
     REPO_ROOT=\"\$HOME/src/VGGT-SLAM\"
     python3 \"\$REPO_ROOT\"/image_publisher.py \
